version: '3'

services:
  reports-db:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "reports-db"  
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
